arch = [
    "base",
    "base-devel",
    "linux",
    "linux-firmware",
    "networkmanager",
    "zip",
    "gnupg",
    "pinentry",
    "pinentry-tty",
    "pkgconf",
    "vim",
    "git",
    "curl",
    "wget",
    "gcc",
    "openssl",
]

apt = [
    "build-essential",
    "network-manager",
    "zip",
    "gnupg2",
    "pinentry-tty",
    "pinentry-curses",
    "pkg-config",
    "vim",
    "git",
    "curl",
    "wget",
    "gcc",
    "libssl-dev",
]

mise = ["kubectl", "go"]
