arch = [
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "neovim",
    "eza",
    "ripgrep",
    "lazygit",
    "tmux",
    "go-yq",
    "jq",
    "fzf",
]

apt = [
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "neovim",
    "ripgrep",
    "tmux",
    "yq",
    "jq",
]

cargo = [
    "bat",
    "zoxide",
    "nu",
    "sheldon",
    "tree-sitter-cli",
    "fd-find",
    "eza",
    "lazygit",
]
